# Generated by Django 4.2.11 on 2026-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=64, unique=True, verbose_name='车辆编号')),
                ('brand', models.CharField(max_length=64, verbose_name='品牌')),
                ('series', models.CharField(blank=True, max_length=128, null=True, verbose_name='车系')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='车型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='售价(万元)')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='新车指导价')),
                ('age', models.IntegerField(null=True, verbose_name='车龄(年)')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='里程(万公里)')),
                ('gearbox', models.CharField(blank=True, max_length=32, null=True, verbose_name='变速箱')),
                ('displacement', models.CharField(blank=True, max_length=32, null=True, verbose_name='排量')),
                ('fuel_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='燃油类型')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='颜色')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('register_date', models.DateField(null=True, verbose_name='上牌日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '二手车信息',
                'verbose_name_plural': '二手车信息',
                'db_table': 'car_info',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='品牌')),
                ('age', models.IntegerField(verbose_name='车龄(年)')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='里程(万公里)')),
                ('gearbox', models.CharField(blank=True, max_length=32, null=True, verbose_name='变速箱')),
                ('displacement', models.CharField(blank=True, max_length=32, null=True, verbose_name='排量')),
                ('fuel_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='燃油类型')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='新车指导价')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预测价格(万元)')),
                ('model_type', models.CharField(choices=[('sklearn', 'Scikit-learn 随机森林'), ('spark_mllib', 'Spark MLlib 随机森林')], default='sklearn', max_length=32, verbose_name='模型类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
            ],
            options={
                'verbose_name': '价格预测记录',
                'verbose_name_plural': '价格预测记录',
                'db_table': 'prediction_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='StatAgePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(unique=True, verbose_name='车龄(年)')),
                ('car_count', models.IntegerField(default=0, verbose_name='车辆数量')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='平均售价')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车龄价格统计',
                'verbose_name_plural': '车龄价格统计',
                'db_table': 'stat_age_price',
                'ordering': ['age'],
            },
        ),
        migrations.CreateModel(
            name='StatBrandPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, unique=True, verbose_name='品牌')),
                ('car_count', models.IntegerField(default=0, verbose_name='车辆数量')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='平均售价')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='最低售价')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='最高售价')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌价格统计',
                'verbose_name_plural': '品牌价格统计',
                'db_table': 'stat_brand_price',
                'ordering': ['-avg_price'],
            },
        ),
        migrations.CreateModel(
            name='StatPriceDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=64, unique=True, verbose_name='价格区间')),
                ('car_count', models.IntegerField(default=0, verbose_name='车辆数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '价格分布统计',
                'verbose_name_plural': '价格分布统计',
                'db_table': 'stat_price_distribution',
            },
        ),
    ]
